### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pizzav-xyz**
## Description

updated Contributions to the discord 

## Related Issue(s)

Fixes #

## Release Notes

```release-note
```

### CODE REVIEW

**Comment by pizzav-xyz** [comment]
this should change at https://docs.polyfrost.cc/oneconfig/#contributions

**Comment by nextdayy** [comment]
it's better to use that link than the discord link incase we no longer have the perk (which sometimes happens if people don't boost enough)

**Comment by pizzav-xyz** [comment]
> it's better to use that link than the discord link incase we no longer have the perk (which sometimes happens if people don't boost enough)

that link doesnt work

**Comment by pizzav-xyz** [comment]
This polyfrost.cc page can’t be found

**Comment by nextdayy** [comment]
it does? there must be something wrong with your internet setup.

**Comment by pizzav-xyz** [comment]
> 



> it does? there must be something wrong with your internet setup.

hmm

**Pull request closed without merging**
